module.exports.CHANNEL_INVITATION_ADDED = "CHANNEL_INVITATION_ADDED";
module.exports.CHANNEL_INVITATION_ACCEPTED = "CHANNEL_INVITATION_ACCEPTED";
module.exports.CHANNEL_INVITATION_REJECTED = "CHANNEL_INVITATION_REJECTED";
module.exports.CHANNEL_NOTIFICATION_VIEWED = "CHANNEL_NOTIFICATION_VIEWED";
module.exports.CHANNEL_MESSAGE_ADDED = "CHANNEL_MESSAGE_ADDED";
module.exports.CHANNEL_FLAGGED = "CHANNEL_FLAGGED";
module.exports.CHANNEL_UPDATED = "CHANNEL_UPDATED";
module.exports.CHANNEL_ADDED = "CHANNEL_ADDED";
